(function(g){var window=this;var JEa=function(a,b){return g.Yb(a,b)},c6=function(a){g.Yn(a,"zx",g.yc());
return a},d6=function(a,b,c){g.Ga(c)||(c=[String(c)]);
g.ao(a.o,b,c)},KEa=function(a,b){var c=[];
g.Hl(b,function(d){try{var e=g.CE.prototype.A.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.v(e)?g.BE(e)&&c.push(d):c.push(d)},a);
return c},LEa=function(a,b){var c=KEa(a,b);
(0,g.E)(c,function(d){g.CE.prototype.remove.call(this,d)},a)},MEa=function(a){if(a.Kd){if(a.Kd.locationOverrideToken)return{locationOverrideToken:a.Kd.locationOverrideToken};
if(null!=a.Kd.latitudeE7&&null!=a.Kd.longitudeE7)return{latitudeE7:a.Kd.latitudeE7,longitudeE7:a.Kd.longitudeE7}}return null},NEa=function(a,b,c,d){var e=new g.Pn(null,void 0);
a&&g.Qn(e,a);b&&g.Rn(e,b);c&&g.Sn(e,c);d&&g.Tn(e,d);return e},e6=function(a,b){g.vF[a]=!0;
var c=g.tF();c&&c.publish.apply(c,arguments);g.vF[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.C=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Jn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",OEa(this,a.capabilities||""),PEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},OEa=function(a,b){a.capabilities.clear();
(0,g.re)(b.split(","),g.Ma(JEa,QEa)).forEach(function(c){a.capabilities.add(c)})},PEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},REa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},SEa=function(a){return new g6(a)},TEa=function(a){return g.Ga(a)?(0,g.K)(a,SEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Ga(a)?"["+(0,g.K)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},UEa=function(a){return(0,g.K)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.Ta(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.Ta(a,function(c){return h6(c,b)})},VEa=function(){var a=(0,g.JI)();
a&&LEa(a,a.o.be(!0))},n6=function(){var a=g.MI("yt-remote-connected-devices")||[];
g.sb(a);return a},WEa=function(a){if(g.Za(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.K)(a,function(d,e){return 0==e?d:d.substring(c.length)})},XEa=function(a){g.LI("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.MI("yt-remote-device-id");a||(a=k6(),g.LI("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.Ya(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.Ya(a,b);g.OI()&&g.ub(a,b);a=WEa(a);if(g.Za(a))try{g.kI("remote_sid")}catch(c){}else try{g.jI("remote_sid",a.join(","),-1)}catch(c){}},YEa=function(){return g.MI("yt-remote-session-browser-channel")},ZEa=function(){return g.MI("yt-remote-local-screens")||[]},$Ea=function(){g.LI("yt-remote-lounge-token-expiration",!0,86400)},aFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.K)(ZEa(),function(d){return d.loungeToken}),c=(0,g.K)(a,function(d){return d.loungeToken});
(0,g.Uj)(c,function(d){return!g.Ya(b,d)})&&$Ea();
g.LI("yt-remote-local-screens",a,31536E3)},bFa=function(a,b){g.LI("yt-remote-session-browser-channel",a);
g.LI("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.Ya(c,d)||c.push(d);XEa(c);q6()},r6=function(a){a||(g.NI("yt-remote-session-screen-id"),g.NI("yt-remote-session-video-id"));
q6();a=n6();g.db(a,p6());XEa(a)},cFa=function(){if(!s6){var a=g.NE();
a&&(s6=new g.wE(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},dFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?eFa(a.shift(),function(){u6(a)}):v6()},fFa=function(a){return"chrome-extension://"+a+w6},eFa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=dFa();
a&&a(!1,"No cast extension found")},hFa=function(){if(gFa){var a=2,b=dFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;eFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},iFa=function(){hFa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.L.call(this);
this.F=null!=c?(0,g.C)(a,c):a;this.Ed=b;this.D=(0,g.C)(this.aL,this);this.o=!1;this.A=0;this.C=this.Fa=null;this.B=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.C=b;this.G=c;this.F=d||1;this.B=45E3;this.Z=new g.fo(this);this.A=new g.bh;this.A.setInterval(250)},kFa=function(a,b,c){a.ik=1;
a.Bh=c6(b.clone());a.pj=c;a.D=!0;jFa(a,null)},A6=function(a,b,c,d,e){a.ik=1;
a.Bh=c6(b.clone());a.pj=null;a.D=c;e&&(a.PF=!1);jFa(a,d)},jFa=function(a,b){a.bl=(0,g.J)();
B6(a);a.fi=a.Bh.clone();d6(a.fi,"t",a.F);a.jo=0;a.Xc=a.o.gu(a.o.Xn()?b:null);0<a.Nu&&(a.ur=new g.tm((0,g.C)(a.aH,a,a.Xc),a.Nu));a.Z.X(a.Xc,"readystatechange",a.eV);var c=a.Oi?g.hc(a.Oi):{};a.pj?(a.qs="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.fi,a.qs,a.pj,c)):(a.qs="GET",a.PF&&!g.fe&&(c.Connection="close"),a.Xc.send(a.fi,a.qs,null,c));a.o.Cf(1)},nFa=function(a,b,c){for(var d=!0;!a.wi&&a.jo<c.length;){var e=lFa(a,c);
if(e==C6){4==b&&(a.Ch=4,D6(15),d=!1);break}else if(e==mFa){a.Ch=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Ch=1,D6(17),d=!1);a.If=a.If&&d;d||(F6(a),G6(a))},lFa=function(a,b){var c=a.jo,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return mFa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.jo=d+c;return e},pFa=function(a,b){a.bl=(0,g.J)();
B6(a);var c=b?window.location.hostname:"";a.fi=a.Bh.clone();g.Yn(a.fi,"DOMAIN",c);g.Yn(a.fi,"t",a.F);try{a.Lf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Ch=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in oFa)k=H6[l]=oFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Ed(g.Uc("b/12014412"),d+"</body></html>");a.Lf.open();a.Lf.write(g.vd(c));a.Lf.close();a.Lf.parentWindow.m=(0,g.C)(a.mU,a);a.Lf.parentWindow.d=(0,g.C)(a.eF,a,!0);a.Lf.parentWindow.rpcClose=(0,g.C)(a.eF,a,!1);c=a.Lf.createElement("DIV");a.Lf.parentWindow.document.body.appendChild(c);d=g.id(a.fi.toString());d=g.sc(g.fd(d));d=g.Ed(g.Uc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Fd(c,d);a.o.Cf(1)},B6=function(a){a.Hy=(0,g.J)()+a.B;
qFa(a,a.B)},qFa=function(a,b){if(null!=a.Cl)throw Error("WatchDog timer not null");
a.Cl=I6((0,g.C)(a.BU,a),b)},J6=function(a){a.Cl&&(g.y.clearTimeout(a.Cl),a.Cl=null)},G6=function(a){a.o.SB()||a.wi||a.o.Uq(a)},F6=function(a){J6(a);
g.Of(a.ur);a.ur=null;a.A.stop();g.lo(a.Z);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Lf&&(a.Lf=null)},E6=function(a,b){try{a.o.XE(a,b),a.o.Cf(4)}catch(c){}},sFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;rFa(a,b,function(k){k?c(!0):g.y.setTimeout(function(){sFa(a,b,c,d,f)},f)})}},rFa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.y.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},tFa=function(a){this.o=a;
this.A=new y6},uFa=function(a){var b=L6(a.o,a.Ql,"/mail/images/cleardot.gif");
c6(b);sFa(b.toString(),5E3,(0,g.C)(a.aK,a),3,2E3);a.Cf(1)},N6=function(a){var b=a.o.I;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.me=new z6(a,void 0,void 0,void 0),a.me.Oi=a.Lu,b=a.o,b=L6(b,b.Xn()?a.Jm:null,a.Mu),D6(5),!g.de||g.Mc(10))d6(b,"TYPE","xmlhttp"),A6(a.me,b,!1,a.Jm,!1);else{d6(b,"TYPE","html");var c=a.me;a=!!a.Jm;c.ik=3;c.Bh=c6(b.clone());pFa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.B=[];this.D=new y6;this.H=a||null;this.I=null!=b?b:null;this.F=c||!1},vFa=function(a,b){this.o=a;
this.map=b;this.context=null},wFa=function(a){g.Qf.call(this,"statevent",a)},xFa=function(a,b){g.Qf.call(this,"timingevent",a);
this.size=b},yFa=function(a){g.Qf.call(this,"serverreachability",a)},BFa=function(a){zFa(a);
if(3==a.o){var b=a.An++,c=a.Ap.clone();g.Yn(c,"SID",a.C);g.Yn(c,"RID",b);g.Yn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.C,b,void 0);b.ik=2;b.Bh=c6(c.clone());(new Image).src=b.Bh;b.bl=(0,g.J)();B6(b)}AFa(a)},CFa=function(a){a.wK(1,0);
a.Ap=L6(a,null,a.Ku);Q6(a)},zFa=function(a){a.rh&&(a.rh.abort(),a.rh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Cg&&(g.y.clearTimeout(a.Cg),a.Cg=null);R6(a);a.ge&&(a.ge.cancel(),a.ge=null);a.vh&&(g.y.clearTimeout(a.vh),a.vh=null)},DFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new vFa(a.YP++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ge||a.vh||(a.vh=I6((0,g.C)(a.dF,a),0),a.Zj=0)},FFa=function(a,b){if(1==a.o){if(!b){a.An=Math.floor(1E5*Math.random());
var c=a.An++,d=new z6(a,"",c,void 0);d.Oi=null;var e=S6(a),f=a.Ap.clone();g.Yn(f,"RID",c);g.Yn(f,"CVER","1");P6(a,f);kFa(d,f,e);a.ge=d;a.o=2}}else 3==a.o&&(b?EFa(a,b):0==a.A.length||a.ge||EFa(a))},EFa=function(a,b){if(b)if(6<a.zi){a.A=a.B.concat(a.A);
a.B.length=0;var c=a.An-1;var d=S6(a)}else c=b.G,d=b.pj;else c=a.An++,d=S6(a);var e=a.Ap.clone();g.Yn(e,"SID",a.C);g.Yn(e,"RID",c);g.Yn(e,"AID",a.Bk);P6(a,e);c=new z6(a,a.C,c,a.Zj+1);c.Oi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ge=c;kFa(c,e,d)},P6=function(a,b){if(a.Dd){var c=a.Dd.yB();
c&&g.Mb(c,function(d,e){g.Yn(b,e,d)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.zi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.zi?e:f-d;try{g.Mb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.A.splice(0,b));
return c.join("&")},GFa=function(a){a.Bc||a.Cg||(a.G=1,a.Cg=I6((0,g.C)(a.cF,a),0),a.Pj=0)},T6=function(a){if(a.Bc||a.Cg||3<=a.Pj)return!1;
a.G++;a.Cg=I6((0,g.C)(a.cF,a),HFa(a,a.Pj));a.Pj++;return!0},M6=function(a,b,c){a.ms=c;
a.Vf=b.Qg;a.F||CFa(a)},R6=function(a){null!=a.Ci&&(g.y.clearTimeout(a.Ci),a.Ci=null)},HFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Dd&&(c=null);var d=(0,g.C)(a.UV,a);c||(c=new g.Pn("//www.google.com/images/cleardot.gif"),c6(c));rFa(c.toString(),1E4,d)}else D6(2);IFa(a,b)},IFa=function(a,b){a.o=0;
a.Dd&&a.Dd.xA(b);AFa(a);zFa(a)},AFa=function(a){a.o=0;
a.Vf=-1;if(a.Dd)if(0==a.B.length&&0==a.A.length)a.Dd.St();else{g.ib(a.B);var b=g.ib(a.A);a.B.length=0;a.A.length=0;a.Dd.St(b)}},L6=function(a,b,c){var d=g.Zn(c);
if(""!=d.A)b&&g.Rn(d,b+"."+d.A),g.Sn(d,d.D);else{var e=window.location;d=NEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.km&&g.Mb(a.km,function(f,k){g.Yn(d,k,f)});
g.Yn(d,"VER",a.zi);P6(a,d);return d},I6=function(a,b){if(!g.Ia(a))throw Error("Fn must not be null and must be a function");
return g.y.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new wFa(V6,a))},JFa=function(){},KFa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.L.call(this);
this.o=new g.U(this.cU,0,this);g.M(this,this.o);this.Ed=5E3;this.A=0;if(g.Ia(a))b&&(a=(0,g.C)(a,b));else if(a&&g.Ia(a.handleEvent))a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},X6=function(a,b,c){this.K=a;
this.F=b;this.C=new g.vE;this.A=new W6(this.yW,this);this.o=this.jb=null;this.Bb=!1;this.D=null;this.I="";this.H=this.B=0;this.G=[];this.L=c||!1},LFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ms,sessionId:a.o.C,arrayId:a.o.Bk}},MFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&FFa(a.o),BFa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},NFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.qh(a)||"";b&&(this.port=":"+b);this.domain=g.ph(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ib(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.v(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.zh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ma(a.B,d,!0),onError:g.Ma(a.C,e),Hd:g.Ma(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.eG(b,a)},RFa=function(){var a=OFa;
PFa();b7.push(a);QFa(b7)},c7=function(a,b){PFa();
var c=b7,d=SFa(a,String(b));g.Za(c)?TFa(d):(QFa(c),(0,g.E)(c,function(e){e(d)}))},PFa=function(){b7||(b7=g.z("yt.mdx.remote.debug.handlers_")||[],g.Da("yt.mdx.remote.debug.handlers_",b7,void 0))},TFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},QFa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.E)(a,function(f){f(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},SFa=function(a,b){var c=((0,g.J)()-UFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.xH.call(this);
this.G=a;this.o=[]},VFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},WFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.re)(a.o,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=VFa(a,b[d])||c;return c},XFa=function(a,b){var c=a.o.length;
a.o=(0,g.re)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.xH.call(this);
this.F=a;this.D=b;this.C=c;this.B=d;this.A=0;this.o=null;this.Fa=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.C=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},YFa=function(a){if(a.o.length){var b=(0,g.K)(a.o,function(d){return d.id}),c=$6(a.C,"/pairing/get_lounge_token_batch");
a7(a.C,c,{screen_ids:b.join(",")},(0,g.C)(a.oL,a),(0,g.C)(a.nL,a))}},i7=function(a){var b=TEa(ZEa());
b=(0,g.re)(b,function(c){return!c.uuid});
return WFa(a,b)},k7=function(a,b){aFa((0,g.K)(a.o,REa));
b&&$Ea()},m7=function(a,b){g.xH.call(this);
this.F=b;var c=g.MI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ya(c,l)}this.o=d;this.D=a;this.C=this.B=NaN;this.A=null;l7("Initialized with "+g.hh(this.o))},ZFa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Sb(b)!=g.Sb(a.o))var c=!1;
else{c=g.Vb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.hh(a.o)),a.o=b,a.U("screenChange"));$Fa(a)},o7=function(a){isNaN(a.C)||g.sF(a.C);
a.C=g.qF((0,g.C)(a.yx,a),0<a.B&&a.B<(0,g.J)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},aGa=function(a){var b={};
(0,g.E)(a.F(),function(c){c.token?b[c.token]=c.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},$Fa=function(a){a=g.Vb(g.Nb(a.o,function(b){return b}));
g.sb(a);a.length?g.LI("yt-remote-online-screen-ids",a.join(","),60):g.NI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.C=null;this.B=[];this.D={};bGa(this)},dGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.xe();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);ZFa(a.A,l,function(m){e(m?l:null)})}else c?cGa(a,c,(0,g.C)(function(m){var n=q7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));ZFa(this.A,n,function(p){e(p?n:null)})},a),f):e(null)},eGa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},cGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.eG($6(a.F,"/pairing/get_lounge_token_batch"),e)},fGa=function(a){a.o=a.C.xe();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},bGa=function(a){r7(a);
a.C=new j7(a.F);a.C.subscribe("screenChange",(0,g.C)(a.BL,a));fGa(a);a.B=TEa(g.MI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.B));a.A=new m7(a.F,(0,g.C)(a.xe,a,!0));a.A.subscribe("screenChange",(0,g.C)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.LI("yt-remote-automatic-screen-cache",(0,g.K)(a.B,REa)));r7(a);a.D[b.uuid]=b.id;g.LI("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.MI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.xH.call(this);
this.M=c;this.I=a;this.A=b;this.C=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.B=0;this.F=(0,g.C)(this.FW,this);this.D=(0,g.C)(this.NU,this);this.B=g.qF((0,g.C)(function(){gGa(this,null)},this),12E4)},hGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.hh(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.A,(0,g.C)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.hh(b))},gGa=function(a,b){g.sF(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.C||a.C.id!=b){var c=(0,g.C)(a.Vq,a),d=(0,g.C)(a.De,a);a.JB(b,c,d,5)}}else a.De(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.B=this.H=null;this.K="";this.V=c;this.D=null;this.G=g.A;this.F=NaN;this.L=(0,g.C)(this.IW,this);this.o=g.A},iGa=function(a){a.o=a.I.fH(a.K,a.A.label,a.A.friendlyName,(0,g.C)(function(b){this.o=g.A;
this.Vq(b)},a),(0,g.C)(function(b){this.o=g.A;
this.De(b)},a))},jGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.V;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}cFa()&&(b.env_useStageMdx=1);return g.xh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.qF((0,g.C)(this.Dk,this,null),150)},x7=function(a,b,c,d){g.xH.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.C=[];this.B=(0,g.C)(this.iT,this)},kGa=function(a,b){return b?g.Ta(a.C,function(c){return h6(b,c.label)},a):null},y7=function(a){c7("Controller",a)},OFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.C.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Of(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.C)(a.aF,a,b)),b.C?a.U("yt-remote-cast2-session-change",b.C):c&&a.o.Dk(null)):a.U("yt-remote-cast2-session-change",null))},lGa=function(a){var b=a.A.eH(),c=a.o&&a.o.A;
a=(0,g.K)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=kGa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},rGa=function(a,b,c,d,e,f,k){mGa()?nGa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?oGa(a,c):(window.__onGCastApiAvailable=function(l,m){l?oGa(a,c):(D7("Failed to load cast API: "+m),E7(!1),C7(!1),g.NI("yt-remote-cast-available"),g.NI("yt-remote-cast-receiver"),pGa(),c(!1))},d?g.DF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?iFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(hFa(),u6(qGa.map(fFa))))):B7("Cannot initialize because not running Chrome")},pGa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Da("yt.mdx.remote.cloudview.instance_",null,void 0);sGa(!1);g.yF(G7);G7.length=0},H7=function(){return!!g.MI("yt-remote-cast-installed")},tGa=function(){var a=g.MI("yt-remote-cast-receiver");
return a?a.friendlyName:null},uGa=function(){B7("clearCurrentReceiver");
g.NI("yt-remote-cast-receiver")},vGa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.xF("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},mGa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.oM||a},wGa=function(a,b){F7().init(a,b)},nGa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.LI("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){B7("onReceiverSelected: "+f.friendlyName);
g.LI("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){B7("onReceiverResumed: "+f.friendlyName);
g.LI("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){B7("onSessionChange: "+i6(f));
f||g.NI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Da("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.z("yt.mdx.remote.cloudview.instance_")},oGa=function(a,b){E7(!0);
C7(!1);wGa(a,function(c){c?(sGa(!0),g.AF("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.NI("yt-remote-cast-available"),g.NI("yt-remote-cast-receiver"),pGa());b(c)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.LI("yt-remote-cast-installed",a)},I7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},sGa=function(a){B7("setApiReady_ "+a);
g.Da("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Da("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Zf=!1;this.I=this.H=this.A=this.B=0;this.C=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Zf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.J)();a.B=0;a.A=0;a.H=0;a.I=0;a.C=NaN;a.D=!1},N7=function(a){return a.sb()?((0,g.J)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.J)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.J)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ic(a.o);b.hasPrevious=a.Zf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.C;return b},T7=function(a,b){g.xH.call(this);
this.o=0;this.B=a;this.F=[];this.D=new g.MD;this.C=this.A=null;this.I=(0,g.C)(this.JQ,this);this.G=(0,g.C)(this.En,this);this.H=(0,g.C)(this.IQ,this);this.K=(0,g.C)(this.VQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Py,this),xGa(this))):c=3;0!=c&&(b?this.Py(c):g.qF((0,g.C)(function(){this.Py(c)},this),0));
var d=vGa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.B.getPlayerContextData())},xGa=function(a){(0,g.E)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ma(this.eT,b),this))},a)},yGa=function(a){(0,g.E)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},V7=function(a,b){50>a.D.Jc()&&g.OD(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.B.sendMessage(b,c)},W7=function(a,b){yGa(a);
a.B.setPlayerContextData(R7(b));xGa(a)},S7=function(a,b){a.C&&(a.C.removeUpdateListener(a.I),a.C.removeMediaListener(a.G),a.En(null));
a.C=b;a.C&&(c7("CP","Setting cast session: "+a.C.sessionId),a.C.addUpdateListener(a.I),a.C.addMediaListener(a.G),a.C.media.length&&a.En(a.C.media[0]))},zGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.C)(function(d){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.xH.call(this);
this.D=NaN;this.V=!1;this.K=this.I=this.L=this.M=NaN;this.O=[];this.B=this.G=this.C=this.kb=this.o=null;this.ua=a;this.O.push(g.gH(window,"beforeunload",(0,g.C)(this.eL,this)));this.A=[];this.kb=new L7;this.aa=b.id;this.o=AGa(this,c);this.o.subscribe("handlerOpened",this.NQ,this);this.o.subscribe("handlerClosed",this.KQ,this);this.o.subscribe("handlerError",this.LQ,this);this.o.subscribe("handlerMessage",this.MQ,this);NFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.kb.videoId;
g.OI()&&g.LI("yt-remote-session-video-id",d)},this)},a8=function(a){c7("conn",a)},AGa=function(a,b){return new X6($6(a.ua,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},BGa=function(a){a.D=g.qF((0,g.C)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.sF(a.D);
a.D=NaN},d8=function(a){g.sF(a.M);
a.M=NaN},CGa=function(a){e8(a);
a.L=g.qF((0,g.C)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.sF(a.L);
a.L=NaN},EGa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Y()&&a.kb.reset(),b8(a,1),f8(a,"getNowPlaying"),DGa(a)):a.F(1)},FGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.kb.videoId&&(g.cc(b.params)?a.kb.o=null:a.kb.o=b.params,a.U("remotePlayerChange"))},GGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.kb.listId=b.params.listId||a.kb.listId;Q7(a.kb,c,d);a.U("remoteQueueChange")},IGa=function(a,b){b.params=b.params||{};
GGa(a,b);HGa(a,b);a.U("autoplayDismissed")},HGa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.kb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.kb.playerState&&(c=-1E3);a.kb.playerState=c;c=Number(b.params.loadedTime);a.kb.I=isNaN(c)?0:c;c=Number(b.params.duration);a.kb.H=isNaN(c)?0:c;c=a.kb;var d=Number(b.params.liveIngestionTime);c.C=d;c.D=isNaN(d)?!1:!0;c=a.kb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.kb.playerState?CGa(a):e8(a);a.U("remotePlayerChange")},JGa=function(a,b){if(-1E3!=
a.kb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.kb.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.kb,isNaN(c)?0:c);a.U("remotePlayerChange")}},KGa=function(a,b){var c="true"==b.params.muted;
a.kb.volume=parseInt(b.params.volume,10);a.kb.muted=c;a.U("remotePlayerChange")},LGa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",parseInt(b.params.timeout,10))},MGa=function(a,b){var c="true"==b.params.hasNext;
a.kb.Zf="true"==b.params.hasPrevious;a.kb.hasNext=c;a.U("previousNextChange")},DGa=function(a){g.sF(a.K);
a.K=g.qF((0,g.C)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.hh(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.jd=a;this.A=[];this.A.push(this.jd.$_s("screenChange",(0,g.C)(this.DW,this)));this.A.push(this.jd.$_s("onlineScreenChange",(0,g.C)(this.DS,this)))},RGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.hF("MDX_CONFIG")||b;VEa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),cFa()&&(h8.o="/api/loungedev"));i8||(i8=g.z("yt.mdx.remote.deferredProxies_")||[],g.Da("yt.mdx.remote.deferredProxies_",i8,void 0));NGa();var c=j8();if(!c){var d=new p7(h8);g.Da("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);rGa(a,d,function(m){m?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.Da("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.hh(b)),m8.push(g.xF("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.xF("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.xF("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.xF("yt-remote-cast2-session-change",OGa)),m8.push(g.xF("yt-remote-connection-change",function(m){m?K7(k8(),"YouTube TV"):o8()||(K7(null,null),uGa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.WF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.hh(a)),PGa(a),c.start(),k8()||QGa())},TGa=function(){var a=SGa();
H7()&&g.MI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},SGa=function(){var a=j8().jd.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return UEa(a)},s8=function(){var a=UGa();
!a&&H7()&&tGa()&&(a={key:"cast-selector-receiver",name:tGa()});return a},UGa=function(){var a=SGa(),b=q8();
b||(b=o8());return g.Ta(a,function(c){return b&&h6(b,c.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().xe();return m6(b,a)},OGa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.z("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.z("yt.mdx.remote.currentScreenId_")},VGa=function(a){g.Da("yt.mdx.remote.currentScreenId_",a,void 0)},WGa=function(){return g.z("yt.mdx.remote.connectData_")},n8=function(a){g.Da("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.z("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||VGa("");g.Da("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.E)(i8,function(c){c(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.OI();
if(!a)return null;var b=j8().xe();return m6(b,a)},u8=function(a,b){q8()&&q8();
VGa(a.id);var c=new $7(h8,a,p8());c.connect(b,WGa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},QGa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),uGa(),l8("Skipping connecting because no session screen found."))},NGa=function(){var a=p8();
if(g.cc(a)){a=p6();var b=g.MI("yt-remote-session-name")||"",c=g.MI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Da("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.z("yt.mdx.remote.channelParams_")||{}},PGa=function(a){a?(g.LI("yt-remote-session-app",a.app),g.LI("yt-remote-session-name",a.name)):(g.NI("yt-remote-session-app"),g.NI("yt-remote-session-name"));
g.Da("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.L.call(this);
this.D=a;this.A=b;this.C=new g.uH(this);g.M(this,this.C);this.C.R(b,"onCaptionsTrackListChanged",this.WR);this.C.R(b,"captionschanged",this.HQ);this.C.R(b,"captionssettingschanged",this.sG);this.C.R(b,"videoplayerreset",this.Wq);this.C.R(b,"mdxautoplaycancel",this.ZJ);this.O=this.C.R(b,"onVolumeChange",this.HE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.WE,this);c.subscribe("remotePlayerChange",this.Hn,this);c.subscribe("remoteQueueChange",this.Wq,this);c.subscribe("autoplayUpNext",this.tE,
this);c.subscribe("previousNextChange",this.TE,this);c.subscribe("nowAutoplaying",this.LE,this);c.subscribe("autoplayDismissed",this.sE,this);this.suggestion=null;this.I=new g.GQ(64);this.B=new g.U(this.pG,500,this);g.M(this,this.B);this.F=new g.U(this.qG,1E3,this);g.M(this,this.F);this.L=new x6(this.eW,0,this);g.M(this,this.L);this.G={};this.M=new g.U(this.OG,1E3,this);g.M(this,this.M);this.K=new g.tm(this.EO,1E3,this);g.M(this,this.K);this.V=g.A;this.sG();this.Wq();this.Hn()},z8=function(a,b){a.D.He(b,
a.A.getVideoData().lengthSeconds)},XGa=function(a){z8(a,0);
a.B.stop();A8(a,new g.GQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.kc(c,b));a.o.dG(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.we();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.Hh,MEa(c));A8(a,new g.GQ(1))},YGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{G4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.I;if(!g.MQ(c,b)){var d=g.W(b,2);d!=g.W(a.I,2)&&g.SU(a.A,d);a.I=b;ZGa(a.D,c,b)}},E8=function(a){g.V.call(this,{J:"div",
N:"ytp-remote",P:[{J:"div",N:"ytp-remote-display-status",P:[{J:"div",N:"ytp-remote-display-status-icon",P:[g.jta()]},{J:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.IV(this,250);g.M(this,this.B);this.D=a;this.R(a,"presentingplayerstatechange",this.F);$Ga(this,g.OU(a))},$Ga=function(a,b){if(3==a.D.getPresentingPlayerType()){var c={RECEIVER_NAME:a.D.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.vV('\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):b.sb()||g.W(b,4)?g.vV('\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',c):g.vV('\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.ZW.call(this,"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430",0,a,b);
this.B=a;this.K={};this.R(a,"onMdxReceiversChange",this.M);this.R(a,"presentingplayerstatechange",this.M);this.M()},G8=function(a){g.lV.call(this,a);
this.A={key:k6(),name:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440"};this.B=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.C=this.A;this.pn=new g.GQ(64);this.I=0;this.H=-1;if(!g.oO(g.Y(this.player))){a=this.player;var b=g.vQ(a);b&&(b=b.tn())&&(b=new F8(a,b),g.M(this,b));b=new E8(a);g.M(this,b);g.cV(a,b.element,4)}},ZGa=function(a,b,c){a.pn=c;
a.player.U("presentingplayerstatechange",new g.QQ(c,b))},H8=function(a,b){if(b.key!=a.C.key)if(b.key==a.A.key)t8();
else{a.C=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Aa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Hh,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=MEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.hh(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().xe(),(d=m6(d,b.key))&&u8(d,1))}},oFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},aHa={},QEa={bY:"atp",K2:"ska",X1:"que",f1:"mus",G2:"sus",p_:"dsp",q2:"seq"};
f6.prototype.sh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.C=this.C;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",gFa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),qGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.D(x6,g.L);g.h=x6.prototype;g.h.ZK=function(a){this.B=arguments;this.o=!1;this.Fa?this.C=(0,g.J)()+this.Ed:this.Fa=g.ch(this.D,this.Ed)};
g.h.stop=function(){this.Fa&&(g.dh(this.Fa),this.Fa=null);this.C=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.h.W=function(){this.stop();x6.fa.W.call(this)};
g.h.aL=function(){this.C?(this.Fa=g.ch(this.D,this.C-(0,g.J)()),this.C=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};y6.prototype.stringify=function(a){return g.y.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.y.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Oi=null;g.h.If=!1;g.h.Cl=null;g.h.Hy=null;g.h.bl=null;g.h.ik=null;g.h.Bh=null;g.h.fi=null;g.h.pj=null;g.h.Xc=null;g.h.jo=0;g.h.Lf=null;g.h.qs=null;g.h.Ch=null;g.h.Km=-1;g.h.PF=!0;g.h.wi=!1;g.h.Nu=0;g.h.ur=null;var mFa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.eV=function(a){a=a.target;var b=this.ur;b&&3==g.Jy(a)?b.Gm():this.aH(a)};
g.h.aH=function(a){try{if(a==this.Xc)a:{var b=g.Jy(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.de&&!g.Mc(10)||g.fe&&!g.Lc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Sf&&!g.Ny(this.Xc))break a;this.wi||4!=b||7==c||(8==c||0>=d?this.o.Cf(3):this.o.Cf(2));J6(this);var e=this.Xc.getStatus();this.Km=e;var f=g.Ny(this.Xc);(this.If=200==e)?(4==b&&F6(this),this.D?(nFa(this,b,f),g.Sf&&this.If&&3==b&&(this.Z.X(this.A,"tick",this.ZU),this.A.start())):E6(this,f),this.If&&!this.wi&&(4==b?this.o.Uq(this):
(this.If=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ch=3,D6(13)):(this.Ch=0,D6(14)),F6(this),G6(this))}}catch(k){this.Xc&&g.Ny(this.Xc)}finally{}};
g.h.ZU=function(){var a=g.Jy(this.Xc),b=g.Ny(this.Xc);this.jo<b.length&&(J6(this),nFa(this,a,b),this.If&&4!=a&&B6(this))};
g.h.mU=function(a){I6((0,g.C)(this.lU,this,a),0)};
g.h.lU=function(a){this.wi||(J6(this),E6(this,a),B6(this))};
g.h.eF=function(a){I6((0,g.C)(this.kU,this,a),0)};
g.h.kU=function(a){this.wi||(F6(this),this.If=a,this.o.Uq(this),this.o.Cf(4))};
g.h.cancel=function(){this.wi=!0;F6(this)};
g.h.BU=function(){this.Cl=null;var a=(0,g.J)();0<=a-this.Hy?(2!=this.ik&&this.o.Cf(3),F6(this),this.Ch=2,D6(18),G6(this)):qFa(this,this.Hy-a)};
g.h.getLastError=function(){return this.Ch};g.h=tFa.prototype;g.h.Lu=null;g.h.me=null;g.h.vr=!1;g.h.TB=null;g.h.yp=null;g.h.Rv=null;g.h.Mu=null;g.h.Xe=null;g.h.Qg=-1;g.h.Jm=null;g.h.Ql=null;g.h.connect=function(a){this.Mu=a;a=L6(this.o,null,this.Mu);D6(3);this.TB=(0,g.J)();var b=this.o.H;null!=b?(this.Jm=b[0],(this.Ql=b[1])?(this.Xe=1,uFa(this)):(this.Xe=2,N6(this))):(d6(a,"MODE","init"),this.me=new z6(this,void 0,void 0,void 0),this.me.Oi=this.Lu,A6(this.me,a,!1,null,!0),this.Xe=0)};
g.h.aK=function(a){if(a)this.Xe=2,N6(this);else{D6(4);var b=this.o;b.Vf=b.rh.Qg;U6(b,9)}a&&this.Cf(2)};
g.h.gu=function(a){return this.o.gu(a)};
g.h.abort=function(){this.me&&(this.me.cancel(),this.me=null);this.Qg=-1};
g.h.SB=function(){return!1};
g.h.XE=function(a,b){this.Qg=a.Km;if(0==this.Xe)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Vf=this.Qg;U6(c,2);return}this.Jm=c[0];this.Ql=c[1]}else c=this.o,c.Vf=this.Qg,U6(c,2);else if(2==this.Xe)if(this.vr)D6(7),this.Rv=(0,g.J)();else if("11111"==b){if(D6(6),this.vr=!0,this.yp=(0,g.J)(),c=this.yp-this.TB,!g.de||g.Mc(10)||500>c)this.Qg=200,this.me.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.yp=this.Rv=(0,g.J)(),this.vr=!1};
g.h.Uq=function(){this.Qg=this.me.Km;if(this.me.If)0==this.Xe?this.Ql?(this.Xe=1,uFa(this)):(this.Xe=2,N6(this)):2==this.Xe&&((!g.de||g.Mc(10)?!this.vr:200>this.Rv-this.yp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Xe?D6(9):2==this.Xe&&D6(10);var a=this.o;this.me.getLastError();a.Vf=this.Qg;U6(a,2)}};
g.h.Xn=function(){return this.o.Xn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Cf=function(a){this.o.Cf(a)};g.h=O6.prototype;g.h.km=null;g.h.ge=null;g.h.Bc=null;g.h.Ku=null;g.h.Ap=null;g.h.nA=null;g.h.Np=null;g.h.An=0;g.h.YP=0;g.h.Dd=null;g.h.vh=null;g.h.Cg=null;g.h.Ci=null;g.h.rh=null;g.h.ms=null;g.h.Bk=-1;g.h.IC=-1;g.h.Vf=-1;g.h.Zj=0;g.h.Pj=0;g.h.zi=8;var V6=new g.rg;g.D(wFa,g.Qf);g.D(xFa,g.Qf);g.D(yFa,g.Qf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Ku=b;this.km=c||{};d&&g.v(e)&&(this.km.OSID=d,this.km.OAID=e);this.F?(I6((0,g.C)(this.EA,this,a),100),CFa(this)):this.EA(a)};
g.h.EA=function(a){this.rh=new tFa(this);this.rh.Lu=null;this.rh.A=this.D;this.rh.connect(a)};
g.h.SB=function(){return 0==this.o};
g.h.dF=function(a){this.vh=null;FFa(this,a)};
g.h.cF=function(){this.Cg=null;this.Bc=new z6(this,this.C,"rpc",this.G);this.Bc.Oi=null;this.Bc.Nu=0;var a=this.nA.clone();g.Yn(a,"RID","rpc");g.Yn(a,"SID",this.C);g.Yn(a,"CI",this.ms?"0":"1");g.Yn(a,"AID",this.Bk);P6(this,a);if(!g.de||g.Mc(10))g.Yn(a,"TYPE","xmlhttp"),A6(this.Bc,a,!0,this.Np,!1);else{g.Yn(a,"TYPE","html");var b=this.Bc,c=!!this.Np;b.ik=3;b.Bh=c6(a.clone());pFa(b,c)}};
g.h.XE=function(a,b){if(0!=this.o&&(this.Bc==a||this.ge==a))if(this.Vf=a.Km,this.ge==a&&3==this.o)if(7<this.zi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Ga(c)&&3==c.length)if(0==c[0])a:{if(!this.Cg){if(this.Bc)if(this.Bc.bl+3E3<this.ge.bl)R6(this),this.Bc.cancel(),this.Bc=null;else break a;T6(this);D6(19)}}else this.IC=c[1],0<this.IC-this.Bk&&37500>c[2]&&this.ms&&0==this.Pj&&!this.Ci&&(this.Ci=I6((0,g.C)(this.CQ,this),6E3));else U6(this,11)}else b!=aHa.eZ.o&&U6(this,11);else if(this.Bc==a&&
R6(this),!g.F(b)){c=this.D.parse(b);g.Ga(c);for(var d=0;d<c.length;d++){var e=c[d];this.Bk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.C=e[1],this.Np=e[2],e=e[3],null!=e?this.zi=e:this.zi=6,this.o=3,this.Dd&&this.Dd.zA(),this.nA=L6(this,this.Xn()?this.Np:null,this.Ku),GFa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Dd&&this.Dd.yA(e),this.Pj=0)}}};
g.h.CQ=function(){null!=this.Ci&&(this.Ci=null,this.Bc.cancel(),this.Bc=null,T6(this),D6(20))};
g.h.Uq=function(a){if(this.Bc==a){R6(this);this.Bc=null;var b=2}else if(this.ge==a)this.ge=null,b=1;else return;this.Vf=a.Km;if(0!=this.o)if(a.If)1==b?(b=(0,g.J)()-a.bl,V6.dispatchEvent(new xFa(V6,a.pj?a.pj.length:0,b,this.Zj)),Q6(this),this.B.length=0):GFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Vf)){if(d=1==b)this.ge||this.vh||1==this.o||2<=this.Zj?d=!1:(this.vh=I6((0,g.C)(this.dF,this,a),HFa(this,this.Zj)),this.Zj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.wK=function(a){if(!g.Ya(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.UV=function(a){a?D6(2):(D6(1),IFa(this,8))};
g.h.gu=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Dy;a.H=!1;return a};
g.h.isActive=function(){return!!this.Dd&&this.Dd.isActive(this)};
g.h.Cf=function(a){V6.dispatchEvent(new yFa(V6,a))};
g.h.Xn=function(){return!(!g.de||g.Mc(10))};
g.h=JFa.prototype;g.h.zA=function(){};
g.h.yA=function(){};
g.h.xA=function(){};
g.h.St=function(){};
g.h.yB=function(){return{}};
g.h.isActive=function(){return!0};g.D(W6,g.L);g.h=W6.prototype;g.h.cU=function(){this.Ed=Math.min(3E5,2*this.Ed);this.C();this.A&&this.start()};
g.h.start=function(){var a=this.Ed+15E3*Math.random();g.Cv(this.o,a);this.A=(0,g.J)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Ed=5E3};g.D(X6,JFa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.h.Gk=function(a){return this.C.Pi(a)};
g.h.U=function(a,b){return this.C.U.apply(this.C,arguments)};
g.h.dispose=function(){this.Bb||(this.Bb=!0,g.Of(this.C),MFa(this),g.Of(this.A),this.A=null)};
g.h.la=function(){return this.Bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.I="";this.A.stop();this.D=a||null;this.B=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Dd=null);d.Dd=this;this.o=d;e?this.o.connect(a,b,this.F,e.C,e.Bk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.kc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&DFa(this.o,c)};
g.h.zA=function(){this.A.reset();this.D=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)DFa(this.o,a[b])}this.U("handlerOpened")};
g.h.xA=function(a){var b=2==a&&401==this.o.Vf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.St=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.yB=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.D&&g.kc(a,this.D);return a};
g.h.yA=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),BFa(this.o)):this.U("handlerMessage",new KFa(a[0],a[1]))};
g.h.yW=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.ge&&b++;0!=b||this.connect(this.D,this.B)};Z6.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var UFa=(0,g.J)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.D(g7,g.xH);g7.prototype.xe=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.D(h7,g.xH);var bHa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Fa)&&this.dH()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Fa)||(g.sF(this.Fa),this.Fa=NaN)};
g.h.W=function(){this.stop();h7.fa.W.call(this)};
g.h.dH=function(){this.Fa=NaN;this.o=g.eG($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.C)(this.AW,this),onError:(0,g.C)(this.zW,this),Hd:(0,g.C)(this.BW,this)})};
g.h.AW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.B;this.U("pairingComplete",new g6(c))};
g.h.zW=function(a){this.o=null;a.status&&404==a.status?this.A>=bHa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=bHa[this.A],this.Fa=g.qF((0,g.C)(this.dH,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.BW=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.D(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.MI("yt-remote-lounge-token-expiration")&&YFa(this);g.sF(this.A);this.A=g.qF((0,g.C)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);VFa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||YFa(this)};
g.h.remove=function(a,b){var c=i7(this);XFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.gs=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.W=function(){g.sF(this.A);j7.fa.W.call(this)};
g.h.oL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.nL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.D(m7,g.xH);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.MI("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.J)()-144E5<a?0:a)?o7(this):(this.B=(0,g.J)()+3E5,g.LI("yt-remote-fast-check-period",this.B),this.yx())};
g.h.isEmpty=function(){return g.cc(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Nb(this.o,function(c,d){return c&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.sF(this.C);this.C=NaN;this.A&&(this.A.abort(),this.A=null);m7.fa.W.call(this)};
g.h.yx=function(){g.sF(this.C);this.C=NaN;this.A&&this.A.abort();var a=aGa(this);if(g.Sb(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Vb(a).join(",")},(0,g.C)(this.ET,this,a),(0,g.C)(this.DT,this))}else n7(this,{}),o7(this)};
g.h.ET=function(a,b){this.A=null;var c=g.Vb(aGa(this));if(g.tb(c,g.Vb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.sc("Changing Screen set during request."),this.yx()};
g.h.DT=function(a){this.sc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.sc=function(a){c7("OnlineScreenService",a)};g.D(p7,g7);g.h=p7.prototype;g.h.start=function(){this.C.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.C.add(a,b,c)};
g.h.remove=function(a,b,c){this.C.remove(a,b,c);this.A.update()};
g.h.gs=function(a,b,c,d){this.C.contains(a)?this.C.gs(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.xe=function(a){return a?this.o:g.gb(this.o,(0,g.re)(this.B,function(b){return!this.contains(b)},this))};
g.h.eH=function(){return(0,g.re)(this.xe(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.fH=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.C)(function(k){g.Of(f);d(q7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Of(f);e(k)});
f.start();return(0,g.C)(f.stop,f)};
g.h.EW=function(a,b,c,d){g.eG($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){var k=new g6(f.screen||{});if(!k.name||eGa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);eGa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(q7(this,k))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
Hd:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Of(this.C);g.Of(this.A);p7.fa.W.call(this)};
g.h.BL=function(){fGa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.D(s7,g.xH);g.h=s7.prototype;g.h.Vq=function(a){this.C=a;this.U("sessionScreen",this.C)};
g.h.De=function(a){this.la()||(a&&t7(this,""+a),this.C=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.hH=function(){return null};
g.h.Kx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Kx("");s7.fa.W.call(this)};g.D(u7,s7);g.h=u7.prototype;g.h.Jx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);hGa(this)};
g.h.Dk=function(a){this.info("launchWithParams no-op for Cast: "+g.hh(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.C)(function(){this.De()},this),(0,g.C)(function(){this.De(Error("Failed to stop receiver app."))},this)):this.De(Error("Stopping cast device witout session."))};
g.h.Kx=g.A;g.h.W=function(){this.info("disposeInternal");g.sF(this.B);this.B=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.fa.W.call(this)};
g.h.NU=function(a,b){if(!this.la())if(b){var c=g.yy(b);if(g.Ja(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.hh(c));switch(d){case "mdxSessionStatus":gGa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.JB=function(a,b,c,d){dGa(this.I,this.A.label,a,this.A.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.qF((0,g.C)(this.JB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.hH=function(){return this.o};
g.h.FW=function(a){this.la()||a||(t7(this,"Cast session died."),this.De())};g.D(v7,s7);g.h=v7.prototype;g.h.Jx=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.Dk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.A;g.sF(this.F);this.B?this.B.stop((0,g.C)(this.De,this,null),(0,g.C)(this.De,this,"Failed to stop DIAL device.")):this.De()};
g.h.W=function(){this.o();this.o=g.A;g.sF(this.F);this.B&&this.B.removeUpdateListener(this.L);this.B=null;v7.fa.W.call(this)};
g.h.IW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.A,this.De())};
g.h.vv=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,jGa(this));a(b);iGa(this)}else this.G=(0,g.C)(function(){g.sF(this.F);this.G=g.A;this.F=NaN;var c=new chrome.cast.DialLaunchResponse(!0,jGa(this));a(c);iGa(this)},this),this.F=g.qF((0,g.C)(function(){this.G()},this),100)};
g.h.PM=function(a,b,c){dGa(this.I,this.H.receiver.label,a,this.A.friendlyName,(0,g.C)(function(d){d&&d.token?(this.Vq(d),b(new chrome.cast.DialLaunchResponse(!1))):this.vv(b,c)},this),(0,g.C)(function(d){t7(this,"Failed to get DIAL screen: "+d);
this.vv(b,c)},this))};g.D(w7,s7);w7.prototype.stop=function(){this.De()};
w7.prototype.Jx=g.A;w7.prototype.Dk=function(){g.sF(this.o);this.o=NaN;var a=m6(this.I.xe(),this.A.label);a?this.Vq(a):this.De(Error("No such screen"))};
w7.prototype.W=function(){g.sF(this.o);this.o=NaN;w7.fa.W.call(this)};g.D(x7,g.xH);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.C)(this.ZE,this),(0,g.C)(this.mT,this),d,e);c.customDialLaunchCallback=(0,g.C)(this.kR,this);chrome.cast.initialize(c,(0,g.C)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.B),RFa(),this.A.subscribe("onlineScreenChange",(0,g.C)(this.gH,this)),this.C=lGa(this),chrome.cast.setCustomReceivers(this.C,g.A,(0,g.C)(function(f){this.sc("Failed to set initial custom receivers: "+g.hh(f))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.C)(function(f){this.sc("Failed to initialize API: "+g.hh(f));
b(!1)},this))};
g.h.CV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.C;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.xe(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=kGa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.A,(0,g.C)(function(e){this.sc("Failed to set initial custom receivers: "+g.hh(e))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Kx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.EV=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.Dk(a):this.sc("Setting connection data without a session")};
g.h.HW=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.ZE,this),(0,g.C)(this.IT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.C)(this.gH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);g.db(g.z("yt.mdx.remote.debug.handlers_")||[],OFa);g.Of(this.o);x7.fa.W.call(this)};
g.h.sc=function(a){c7("Controller",a)};
g.h.aF=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.iT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.C&&this.U("yt-remote-cast2-session-change",this.o.C);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.kR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.C)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.C),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.C)(b.PM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.C)(b.vv,b))};
g.h.ZE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.xe(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Of(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.C)(this.aF,this,this.o)),this.o.Dk(null));this.o.Jx(a)}}};
g.h.GW=function(){return this.o?this.o.hH():null};
g.h.IT=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.hh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.mT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.gH=function(){this.la()||(this.C=lGa(this),y7("Updating custom receivers: "+g.hh(this.C)),chrome.cast.setCustomReceivers(this.C,g.A,(0,g.C)(function(){this.sc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.EV;x7.prototype.setConnectedScreenStatus=x7.prototype.CV;x7.prototype.stopSession=x7.prototype.HW;x7.prototype.getCastSession=x7.prototype.GW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Zf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.C=a.liveIngestionTime,this.D=!isNaN(this.C))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.D(T7,g.xH);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.A,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.A,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.A,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.Ma(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.A,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.C){if(c.volume!=a){var d=Math.round(a)/100;this.C.setReceiverVolumeLevel(d,(0,g.C)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.C.setReceiverMuted(b,(0,g.C)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Ma(this.setVolume,a,b))};
g.h.dG=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.hh(b.style),g.kc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Ma(this.dG,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();Y7(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=U7(this);d.audioTrackId=c;W7(this,d)}else V7(this,g.Ma(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.v(b)&&(O7(l,b),m.currentTime=b);g.v(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.hh(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.fr=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Ma(this.fr,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Ma(this.nextVideo,a,b))};
g.h.YA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.YA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.fa.dispose.call(this)};
g.h.W=function(){yGa(this);this.B=null;this.D.clear();S7(this,null);T7.fa.W.call(this)};
g.h.Py=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.PD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.eT=function(a,b){this.U(a,b)};
g.h.JQ=function(a){if(!a)this.En(null),S7(this,null);else if(this.C.receiver.volume){a=this.C.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.En=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),zGa(this),this.U("remotePlayerChange")};
g.h.IQ=function(a){a?(zGa(this),this.U("remotePlayerChange")):this.En(null)};
g.h.fy=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.VQ=function(){var a=vGa();a&&S7(this,a)};
g.h.sc=function(a){c7("CP",a)};g.D($7,g.xH);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.v(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.v(k)&&(l.currentIndex=k);c&&(this.kb.listId=c);this.kb.videoId=d;this.kb.index=k||0;this.kb.state=3;O7(this.kb,m);this.B="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.hh(l));this.o.connect({method:"setPlaylist",
params:g.hh(l)},a,YEa())}else a8("Connecting without params"),this.o.connect({},a,YEa());BGa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.fa.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.sF(this.I);this.I=NaN;g.sF(this.K);this.K=NaN;this.C=null;g.hH(this.O);this.O.length=0;this.o.dispose();$7.fa.W.call(this);this.B=this.G=this.A=this.kb=this.o=null};
g.h.eL=function(){this.F(2)};
g.h.NQ=function(){a8("Channel opened");this.V&&(this.V=!1,d8(this),this.M=g.qF((0,g.C)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
bFa(LFa(this.o),this.aa)};
g.h.KQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.LQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.V=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.MQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.hh(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.yy(a.params.devices);this.A=(0,g.K)(a,function(c){return new f6(c)});
a=!!g.Ta(this.A,function(c){return"LOUNGE_SCREEN"==c.type});
EGa(this,a);break;case "loungeScreenDisconnected":g.eb(this.A,function(c){return"LOUNGE_SCREEN"==c.type});
EGa(this,!1);break;case "remoteConnected":var b=new f6(g.yy(a.params.device));g.Ta(this.A,function(c){return b?c.id==b.id:!1})||g.bb(this.A,b);
break;case "remoteDisconnected":b=new f6(g.yy(a.params.device));g.eb(this.A,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":GGa(this,a);break;case "nowPlaying":IGa(this,a);break;case "onStateChange":HGa(this,a);break;case "onAdStateChange":JGa(this,a);break;case "onVolumeChanged":KGa(this,a);break;case "onSubtitlesTrackChanged":FGa(this,a);break;case "nowAutoplaying":LGa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":MGa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.mV=function(){if(this.C){var a=this.C;this.C=null;this.kb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Gk;$7.prototype.ia=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ia;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&r6();MFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.ea=function(){var a=this.kb;this.C&&(a=this.kb.clone(),Q7(a,this.C,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.ea;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.kb.videoId&&(this.C=b.videoId,g.sF(this.I),this.I=g.qF((0,g.C)(this.mV,this),5E3));var c=[];this.kb.listId==b.listId&&this.kb.videoId==b.videoId&&this.kb.index==b.index||c.push("remoteQueueChange");this.kb.playerState==b.playerState&&this.kb.volume==b.volume&&this.kb.muted==b.muted&&P7(this.kb)==P7(b)&&g.hh(this.kb.o)==g.hh(b.o)||c.push("remotePlayerChange");this.kb.reset(a);(0,g.E)(c,function(d){this.U(d)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Y=function(){var a=this.o.F.id,b=g.Ta(this.A,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Y;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.J)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ba=function(){return this.B||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ba;$7.prototype.ga=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ga;$7.prototype.ya=function(){if(!isNaN(this.H())){var a=this.o.A;g.Dv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.ya;$7.prototype.ka=function(a,b){f8(this,a,b);DGa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.D(g8,g7);g.h=g8.prototype;g.h.xe=function(a){return this.jd.$_gs(a)};
g.h.contains=function(a){return!!this.jd.$_c(a)};
g.h.get=function(a){return this.jd.$_g(a)};
g.h.start=function(){this.jd.$_st()};
g.h.add=function(a,b,c){this.jd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.jd.$_r(a,b,c)};
g.h.gs=function(a,b,c,d){this.jd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.jd.$_ubk(this.A[a]);this.A.length=0;this.jd=null;g8.fa.W.call(this)};
g.h.DW=function(){this.U("screenChange")};
g.h.DS=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.EW;p7.prototype.$_gsppc=p7.prototype.fH;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.gs;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.xe;p7.prototype.$_gos=p7.prototype.eH;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Gk;var h8=null,i8=null,x8=null,m8=[];g.t(y8,g.L);g.h=y8.prototype;
g.h.W=function(){g.L.prototype.W.call(this);this.B.stop();this.F.stop();this.L.stop();this.V();this.o.unsubscribe("proxyStateChange",this.WE,this);this.o.unsubscribe("remotePlayerChange",this.Hn,this);this.o.unsubscribe("remoteQueueChange",this.Wq,this);this.o.unsubscribe("autoplayUpNext",this.tE,this);this.o.unsubscribe("previousNextChange",this.TE,this);this.o.unsubscribe("nowAutoplaying",this.LE,this);this.o.unsubscribe("autoplayDismissed",this.sE,this);this.o=this.D=null};
g.h.wD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Gm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.HQ=function(a){this.L.ZK(a)};
g.h.eW=function(a){this.wD("control_subtitles_set_track",g.cc(a)?null:a)};
g.h.sG=function(){var a=this.A.getOption("captions","track");g.cc(a)||C8(this,a)};
g.h.HE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Hn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Hn,this)}};
g.h.WR=function(){g.cc(this.G)||YGa(this,this.G);this.H=!1};
g.h.WE=function(a,b){this.F.stop();2==b&&this.qG()};
g.h.Hn=function(){if(B8(this)){this.B.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.jl(1);break;case 1082:case 1083:this.D.jl(0);break;default:this.D.jl(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.GQ(8));this.pG();break;case 1085:case 3:A8(this,new g.GQ(9));break;case 1083:case 0:A8(this,new g.GQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.GQ(4));break;case 2:A8(this,new g.GQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.GQ(64));break;case -1E3:A8(this,new g.GQ(128,{errorCode:"mdx.remoteerror",message:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&
a.kind==b.kind:1)||(this.G=a,YGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.OG()}else XGa(this)};
g.h.TE=function(){this.A.U("mdxpreviousnextchange")};
g.h.Wq=function(){B8(this)||XGa(this)};
g.h.ZJ=function(){this.o.YA()};
g.h.tE=function(a){a&&(a=g.eG("/watch_queue_ajax",{method:"GET",ed:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.C)(this.oU,this)}))&&(this.V=(0,g.C)(a.abort,a))};
g.h.oU=function(a,b){var c=new g.yP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.LE=function(a){isNaN(a)||this.A.U("mdxnowautoplaying",a)};
g.h.sE=function(){this.A.U("mdxautoplaycanceled")};
g.h.EO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.OG=function(){if(B8(this)){var a=U7(this.o);this.C.Ka(this.O);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.O=this.C.R(this.A,"onVolumeChange",this.HE)}};
g.h.pG=function(){this.B.stop();if(!this.o.la()){var a=U7(this.o);a.sb()&&A8(this,new g.GQ(8));z8(this,P7(a));this.B.start()}};
g.h.qG=function(){this.F.stop();this.B.stop();var a=this.o.B.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.t(E8,g.V);E8.prototype.F=function(a){$Ga(this,a.state)};g.t(F8,g.ZW);F8.prototype.M=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.K=g.vb(a,this.G,this),g.$W(this,(0,g.K)(a,this.G)),a=this.B.getOption("remote","currentReceiver"),this.Bf(this.G(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.G=function(a){return a.key};
F8.prototype.Af=function(a){return"cast-selector-receiver"==a?"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c":this.K[a].name};
F8.prototype.ld=function(a){g.ZW.prototype.ld.call(this,a);this.B.setOption("remote","currentReceiver",this.K[a]);this.D.Kb()};g.t(G8,g.lV);g.h=G8.prototype;g.h.create=function(){RGa(g.gO(g.Y(this.player)));this.D.push(g.xF("yt-remote-before-disconnect",this.DQ,this));this.D.push(g.xF("yt-remote-connection-change",this.nT,this));this.D.push(g.xF("yt-remote-receiver-availability-change",this.UE,this));this.D.push(g.xF("yt-remote-auto-connect",this.lT,this));this.D.push(g.xF("yt-remote-receiver-resumed",this.kT,this));this.UE()};
g.h.load=function(){this.player.cancelPlayback();g.lV.prototype.load.call(this);this.B=new y8(this,this.player,this.o);var a=(a=WGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.He(a);ZGa(this,this.pn,this.pn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.C=this.A;g.Pf(this.B,this.o);this.o=this.B=null;g.lV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.yF(this.D);g.lV.prototype.W.call(this)};
g.h.Zh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.wD.apply(this.B,[a].concat(g.ea(c)))};
g.h.jl=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.TK=function(){return this.loaded?this.B.suggestion:null};
g.h.Zf=function(){return this.o?U7(this.o).Zf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.He=function(a,b){this.I=a||0;this.player.U("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Mc():!a.isAdPlaying()&&this.player.Mc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.C+N7(a):a.C,isAtLiveHead:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.B?a.B+N7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.fr=function(){this.o&&this.o.fr()};
g.h.DQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.nT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.C=b,this.load())}else g.Of(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.UE=function(){this.F=[this.A].concat(TGa());var a=s8()||this.A;H8(this,a);this.player.Ca("onMdxReceiversChange")};
g.h.lT=function(){var a=s8();H8(this,a)};
g.h.kT=function(){this.C=s8()};
g.h.Ic=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.C:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.fy=function(){this.o.fy()};
g.h.xc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WZ.remote=G8;})(_yt_player);
